name: Run linters using pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Checkout the repo
      - uses: actions/setup-python@v3 # Setup pre-commit env
      - uses: pre-commit/action@v3.0.0